### ISSUE TITLE
Frontend Testの発火条件見直し

### ISSUE THREAD

**Issue by na2na-p** [na2na-p/sns-app#11]
常に発火してるのよくない

**Comment by na2na-p** [comment]
やった
```yml
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
 ```
